### PR TITLE
Add opening external links in new tab

### PR DESCRIPTION
**Pull request by lex111**
cc @SachaG

### CODE REVIEW

**Comment by SachaG** [comment]
I do use target="_blank" for SPAs where replacing the current tab can disrupt what you're doing, but for a static site I think it's probably not needed… if people can make a mistake they can always click the back button?

**Comment by lex111** [comment]
This is just best practice, since regular external links should open in a new tab (this is expected behavior from the side of users).

**Comment by SachaG** [comment]
I think the concensus is that it's generally a bad idea to use it: https://css-tricks.com/use-target_blank/

**Comment by lex111** [comment]
Alright then.

**Pull request closed without merging**
